apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wanderlust-ui
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Yashdubey455/Wanderlust-Mega-Project.git
    targetRevision: main
    path: kubernetes

  destination:
    server: https://kubernetes.default.svc
    namespace: wanderlust

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
